name = "stone-slab-inventory"
compatibility_date = "2024-01-01"

[env.production]
name = "stone-slab-inventory"
routes = [
  { pattern = "your-domain.com", zone_name = "your-domain.com" }
]

[env.preview]
name = "stone-slab-inventory-preview"

[[env.production.vars]]
NEXT_PUBLIC_APP_VERSION = "1.0.0"

[[env.production.vars]]
NEXT_PUBLIC_ANALYTICS_ENABLED = "true"

[[env.production.vars]]
NEXT_PUBLIC_ERROR_REPORTING_ENABLED = "true"

[[env.production.vars]]
NEXT_PUBLIC_PERFORMANCE_MONITORING_ENABLED = "true"

[[env.production.vars]]
NEXT_PUBLIC_DEBUG_MODE = "false"
